.class public Lcom/pinguo/camera360/lib/umeng/UmengStatistics$Cloud;
.super Ljava/lang/Object;
.source "UmengStatistics.java"
.field private static final CLOUD_5_1:Ljava/lang/String; = "cloud_5_1"
.field private static final CLOUD_5_10:Ljava/lang/String; = "cloud_5_10"
.field private static final CLOUD_5_11:Ljava/lang/String; = "cloud_5_11"
.field private static final CLOUD_5_12:Ljava/lang/String; = "cloud_5_12"
.field private static final CLOUD_5_13:Ljava/lang/String; = "cloud_5_13"
.field private static final CLOUD_5_14:Ljava/lang/String; = "cloud_5_14"
.field private static final CLOUD_5_15:Ljava/lang/String; = "cloud_5_15"
.field private static final CLOUD_5_16:Ljava/lang/String; = "cloud_5_16"
.field private static final CLOUD_5_17:Ljava/lang/String; = "cloud_5_17"
.field private static final CLOUD_5_18:Ljava/lang/String; = "cloud_5_18"
.field private static final CLOUD_5_19:Ljava/lang/String; = "cloud_5_19"
.field private static final CLOUD_5_2:Ljava/lang/String; = "cloud_5_2"
.field private static final CLOUD_5_3:Ljava/lang/String; = "cloud_5_3"
.field private static final CLOUD_5_4:Ljava/lang/String; = "cloud_5_4"
.field private static final CLOUD_5_5:Ljava/lang/String; = "cloud_5_5"
.field private static final CLOUD_5_6:Ljava/lang/String; = "cloud_5_6"
.field private static final CLOUD_5_7:Ljava/lang/String; = "cloud_5_7"
.field private static final CLOUD_5_8:Ljava/lang/String; = "cloud_5_8"
.field private static final CLOUD_5_9:Ljava/lang/String; = "cloud_5_9"
.field private static final CLOUD_BTN_AGREE:Ljava/lang/String; = "agree"
.field private static final CLOUD_BTN_BACK:Ljava/lang/String; = "back"
.field private static final CLOUD_BTN_BIND:Ljava/lang/String; = "bind"
.field private static final CLOUD_BTN_CANCEL:Ljava/lang/String; = "cancel"
.field private static final CLOUD_BTN_DOWNLOAD:Ljava/lang/String; = "download"
.field private static final CLOUD_BTN_LOGIN:Ljava/lang/String; = "login"
.field private static final CLOUD_BTN_NOT_AGREE:Ljava/lang/String; = "not_agree"
.field private static final CLOUD_BTN_NOT_BIND:Ljava/lang/String; = "not_bind"
.field private static final CLOUD_BTN_OPEN:Ljava/lang/String; = "open"
.field private static final CLOUD_BTN_REFRESH:Ljava/lang/String; = "refresh"
.field private static final CLOUD_BTN_REGISRER:Ljava/lang/String; = "register"
.field private static final CLOUD_BTN_SELECT:Ljava/lang/String; = "select"
.field private static final CLOUD_BTN_SHARE:Ljava/lang/String; = "share"
.field private static final CLOUD_REGISTER_FIAL:Ljava/lang/String; = "fial"
.field private static final CLOUD_REGISTER_SUCCESS:Ljava/lang/String; = "success"
.method public constructor <init>()V
.registers 1
invoke-direct {p0}, Ljava/lang/Object;-><init>()V
return-void
.end method