#!/home/chenja/localx/bin/Rscript
#args <- commandArgs(TRUE)

# This script can be used only if data has been generated by "estimated.R"
# and is saved in "cc.Rdata"

rm(list=ls())
library("nnls", lib="/home/jychen/localx/r_packages")

print("charge gap for estimation (0 for 1%, 1 for 2%, etc.)")
charge_gap <- scan(what=integer(0), nmax=1)

print("source filename (w/o .Rdata)")
fin <- scan(what=character(0), nmax=1)

load(paste(fin, ".Rdata", sep=""))
# source data is stored in the object called "cc"
charge_data <- data.frame(cc)

# generate records with specific energy gap
charge_data_gap <- data.frame(charge=charge_data$charge)
apply(array(1:(length(charge_data$charge)-charge_gap)), 1,
      function(x)
        if(toString(charge_data$charge[x+charge_gap])==toString((charge_data$charge[x]-(charge_gap/100)))) {
          charge_data_gap$est_wh[x] <<- sum(charge_data$est_wh[x:(x+charge_gap)])
          charge_data_gap$cpu[x] <<- sum(charge_data$cpu[x:(x+charge_gap)])
          charge_data_gap$screen[x] <<- sum(charge_data$screen[x:(x+charge_gap)])
          charge_data_gap$wifi_rx[x] <<- sum(charge_data$wifi_rx[x:(x+charge_gap)])
          charge_data_gap$wifi_tx[x] <<- sum(charge_data$wifi_tx[x:(x+charge_gap)])
          charge_data_gap$elapse[x] <<- sum(charge_data$elapse[x:(x+charge_gap)])
        } else {
            charge_data_gap$est_wh[x] <<- 0
            charge_data_gap$cpu[x] <<- 0
            charge_data_gap$screen[x] <<- 0
            charge_data_gap$wifi_rx[x] <<- 0
            charge_data_gap$wifi_tx[x] <<- 0
            charge_data_gap$elapse[x] <<- 0
        })

charge_data_gap <- charge_data_gap[-c((length(charge_data$charge)-charge_gap+1):length(charge_data$charge)),]
if(length(which(floor(charge_data_gap$elapse*1e+6)==0)) > 0)
  charge_data_gap <- charge_data_gap[-c(which(floor(charge_data_gap$elapse*1e+6)==0)),]

charge_data_gap$wifi <- charge_data_gap$wifi_rx + charge_data_gap$wifi_tx

# low/high state of wifi (just a guess)
charge_data_gap$wifi_high <- 0
charge_data_gap$wifi_high[which(charge_data_gap$wifi>100.0)] <- 
                         charge_data_gap$wifi[which(charge_data_gap$wifi>100.0)]
charge_data_gap$wifi_low <- 0
charge_data_gap$wifi_low[which(charge_data_gap$wifi<=100.0)] <- 
                         charge_data_gap$wifi[which(charge_data_gap$wifi<=100.0)]


# normalization [0-1]
base_est_wh <- max(charge_data_gap$est_wh)
base_cpu <- max(charge_data_gap$cpu)
base_screen <- max(charge_data_gap$screen)
base_wifi <- max(charge_data_gap$wifi)
base_elapse <- max(charge_data_gap$elapse)

base_wifi_high <- max(charge_data_gap$wifi_high)
base_wifi_low <- max(charge_data_gap$wifi_low)

charge_data_gap_norm <- data.frame(charge=charge_data_gap$charge)
charge_data_gap_norm$est_wh <- charge_data_gap$est_wh/base_est_wh
charge_data_gap_norm$cpu <- charge_data_gap$cpu/base_cpu
charge_data_gap_norm$screen <- charge_data_gap$screen/base_screen

charge_data_gap_norm$wifi <- charge_data_gap$wifi/base_wifi
charge_data_gap_norm$wifi_high <- charge_data_gap$wifi_high/base_wifi_high
charge_data_gap_norm$wifi_low <- charge_data_gap$wifi_low/base_wifi_low

# use transmission rate instead of total data byte sent
#charge_data_gap_norm$wifi <- charge_data_gap$wifi/charge_data_gap$elapse
#charge_data_gap_norm$wifi <- log(charge_data_gap_norm$wifi)/max(log(charge_data_gap_norm$wifi))

charge_data_gap_norm$elapse <- charge_data_gap$elapse/base_elapse

# output
write.csv(charge_data_gap, file=paste("res/", fin, "_", charge_gap, ".csv", sep=""))
write.csv(charge_data_gap_norm, file=paste("res/", fin, "_", charge_gap, "_norm.csv", sep=""))



# plot 
source("my.plots.R")
px <- charge_data_gap_norm$charge
# py: est_wh, cpu, screen, wifi, wifi_high, wifi_low, elapse
py <- as.matrix(charge_data_gap_norm[, -1])
yrange <- range(0, 1.1)
cols <- c(cat042, cat021, cat031, cat051, cat062)
pchs <- pch_hollow[1:5]
ltys <- lty[1:5]

#pdf(file=paste("res/", fin, "_", charge_gap, ".pdf", sep=""))
#png(file=paste("res/", fin, "_", charge_gap, ".png", sep=""))
#par(cex=1.0, lwd=1.5, pch=pchs)
#plot(px, py[,1], col=cols[1], lty=ltys[1], lwd=2.1, type="o", 
#     xlab="charge state", ylab="", ylim=yrange)
#apply(array(2:5), 1, 
#      function(x) lines(px, py[,x], col=cols[x], lty=ltys[x], lwd=2.1, type="o"))

#labs <- c("est_wh", "cpu", "screen", "wifi", "elapse")
#legend(px[1], yrange[1], xjust=1, yjust=0, 
#       labs, cex=0.9, lwd=1.5, col=cols, pch=pchs, lty=ltys)
#dev.off()

#pdf(file=paste("res/", fin, "_", charge_gap, ".pdf", sep=""))
png(file=paste("res/", fin, "_", charge_gap, ".png", sep=""))
par(cex=1.0, lwd=1.5, xpd=T)
# cpu, screen, wifi
pbar <- barplot(t(py[,c(2:4)]), col=cols[2:4], ylim=yrange, beside=T)
# est_wh
lines(pbar[2,], py[,1], col=cols[1], pch=pchs[1], lty=ltys[1], lwd=2.1, type="o")
# est_elapse
lines(pbar[2,], py[,7], col=cols[5], pch=pchs[2], lty=ltys[2], lwd=2.1, type="o")

labs <- c("est_wh", "elapse")
legend(px[1], yrange[2]+0.1, xjust=0, yjust=1, 
       labs, cex=0.9, lwd=1.5, col=cols[c(1, 5)], pch=pchs, lty=ltys)
dev.off()


# linear modeling
#power.lm <- lm(est_wh ~ cpu + screen + wifi_rx + wifi_tx, data=charge_data_gap)
#power.lm_intercept <- lm(est_wh ~ cpu + screen + I(wifi^2) + elapse, data=charge_data_gap_norm)
#power.lm <- lm(est_wh ~ -1 + cpu + screen + wifi + I(wifi^2) + elapse, data=charge_data_gap_norm)
power.lm <- lm(est_wh ~ -1 + cpu + screen + wifi + elapse, data=charge_data_gap_norm)
power.lm_wifi <- lm(est_wh ~ -1 + cpu + screen + wifi_high + wifi_low + elapse, data=charge_data_gap_norm)

#nnls_a <- cbind(charge_data_gap$cpu, charge_data_gap$screen, charge_data_gap$wifi)
#nnls_b <- charge_data_gap$est_wh

nnls_a <- cbind(charge_data_gap_norm$cpu, charge_data_gap_norm$screen, 
                charge_data_gap_norm$wifi, charge_data_gap_norm$elapse)
nnls_b <- charge_data_gap_norm$est_wh
power.nnlslm_elapse <- nnls(nnls_a, nnls_b)
#power.nnlslm_intercept <- nnls(cbind(1, nnls_a), nnls_b)

nnls_a <- cbind(charge_data_gap_norm$cpu, charge_data_gap_norm$screen, 
                charge_data_gap_norm$wifi_high, charge_data_gap_norm$wifi_low, 
                charge_data_gap_norm$elapse)
power.nnlslm_wifi <- nnls(nnls_a, nnls_b)



# test data
#load("cc_test.Rdata")
cc_test$wifi <- cc_test$wifi_rx + cc_test$wifi_tx
write.csv(cc_test, file=paste("res/cc_test_", charge_gap, ".csv", sep=""))

cc_test$cpu <- cc_test$cpu/base_cpu
cc_test$screen <- cc_test$screen/base_screen

cc_test$wifi_high <- 0
cc_test$wifi_high[which(cc_test$wifi>100.0)] <- cc_test$wifi[which(cc_test$wifi>100.0)]
cc_test$wifi_low <- 0
cc_test$wifi_low[which(cc_test$wifi<=100.0)] <- cc_test$wifi[which(cc_test$wifi<=100.0)]
cc_test$wifi_high <- cc_test$wifi_high/base_wifi_high
cc_test$wifi_low <- cc_test$wifi_low/base_wifi_low
cc_test$wifi <- cc_test$wifi/base_wifi

cc_test$elapse <- cc_test$elapse/base_elapse

pred.lm <- predict.lm(power.lm, cc_test)
pred.lm_wifi <- predict.lm(power.lm_wifi, cc_test)

pred.lm <- pred.lm*base_est_wh
pred.accu <- 1 - (abs(pred.lm-cc_test$est_wh)/cc_test$est_wh)

pred.lm_wifi <- pred.lm_wifi*base_est_wh
pred.accu_wifi <- 1 - (abs(pred.lm_wifi-cc_test$est_wh)/cc_test$est_wh)


# print results
print("power.lm")
print(coef(power.lm))
print(cbind("measured"=cc_test$est_wh, "predicted"=pred.lm, "abs accuracy"=pred.accu))

print("power.lm_wifi")
print(coef(power.lm_wifi))
print(cbind("measured"=cc_test$est_wh, "predicted"=pred.lm, "abs accuracy"=pred.accu))


# save object data
#save(list=ls(), file=paste("res/", rda, ".Rdata", sep=""))

#q()

