.class public Lcom/instagram/api/k/a/e;
.super Lcom/instagram/api/k/a/i;
.source "IgAutogenResponse.java"
.field  f:Ljava/util/List;
.field  g:Ljava/lang/String;
.field  h:Ljava/util/List;
.field  i:Ljava/lang/String;
.field  j:Ljava/lang/String;
.field  k:Ljava/lang/String;
.field  l:Z
.method public constructor <init>()V
.registers 1
invoke-direct {p0}, Lcom/instagram/api/k/a/i;-><init>()V
return-void
.end method
.method private static a()V
.registers 2
new-instance v0, Ljava/lang/IllegalStateException;
const-string v1, "should never be called for autogenerated responses"
invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V
throw v0
.end method
.method private b()Lcom/instagram/api/k/a/e;
.registers 1
return-object p0
.end method
.method final a(Lcom/fasterxml/jackson/a/l;)V
.registers 5
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getCurrentToken()Lcom/fasterxml/jackson/a/r;
move-result-object v0
sget-object v1, Lcom/fasterxml/jackson/a/r;->b:Lcom/fasterxml/jackson/a/r;
if-ne v0, v1, :cond_43
new-instance v0, Ljava/util/ArrayList;
invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V
:goto_d
:cond_d
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->nextToken()Lcom/fasterxml/jackson/a/r;
move-result-object v1
sget-object v2, Lcom/fasterxml/jackson/a/r;->c:Lcom/fasterxml/jackson/a/r;
if-eq v1, v2, :cond_40
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getCurrentName()Ljava/lang/String;
move-result-object v1
const-string v2, "errors"
invoke-virtual {v1, v2}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
move-result v1
if-eqz v1, :cond_3c
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->nextToken()Lcom/fasterxml/jackson/a/r;
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getCurrentToken()Lcom/fasterxml/jackson/a/r;
move-result-object v1
sget-object v2, Lcom/fasterxml/jackson/a/r;->d:Lcom/fasterxml/jackson/a/r;
if-ne v1, v2, :cond_d
:goto_2c
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->nextToken()Lcom/fasterxml/jackson/a/r;
move-result-object v1
sget-object v2, Lcom/fasterxml/jackson/a/r;->e:Lcom/fasterxml/jackson/a/r;
if-eq v1, v2, :cond_d
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getText()Ljava/lang/String;
move-result-object v1
invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z
goto :goto_2c
:cond_3c
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->skipChildren()Lcom/fasterxml/jackson/a/l;
goto :goto_d
:cond_40
iput-object v0, p0, Lcom/instagram/api/k/a/e;->h:Ljava/util/List;
:goto_42
return-void
:cond_43
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getCurrentToken()Lcom/fasterxml/jackson/a/r;
move-result-object v0
sget-object v1, Lcom/fasterxml/jackson/a/r;->d:Lcom/fasterxml/jackson/a/r;
if-ne v0, v1, :cond_4f
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->skipChildren()Lcom/fasterxml/jackson/a/l;
goto :goto_42
:cond_4f
invoke-virtual {p1}, Lcom/fasterxml/jackson/a/l;->getText()Ljava/lang/String;
move-result-object v0
iput-object v0, p0, Lcom/instagram/api/k/a/e;->g:Ljava/lang/String;
goto :goto_42
.end method
.method public final bridge synthetic a(Ljava/lang/Object;)V
.registers 2
invoke-static {}, Lcom/instagram/api/k/a/e;->a()V
return-void
.end method
.method final a(Ljava/lang/String;)V
.registers 2
iput-object p1, p0, Lcom/instagram/api/k/a/e;->i:Ljava/lang/String;
return-void
.end method
.method public final f()Ljava/util/List;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->f:Ljava/util/List;
return-object v0
.end method
.method public final g()Ljava/lang/String;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->j:Ljava/lang/String;
return-object v0
.end method
.method public final h()Z
.registers 2
iget-boolean v0, p0, Lcom/instagram/api/k/a/e;->l:Z
return v0
.end method
.method public final i()Ljava/lang/String;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->k:Ljava/lang/String;
return-object v0
.end method
.method public final j()Ljava/lang/String;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->i:Ljava/lang/String;
return-object v0
.end method
.method public final k()Ljava/lang/String;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->g:Ljava/lang/String;
return-object v0
.end method
.method public final l()Ljava/util/List;
.registers 2
iget-object v0, p0, Lcom/instagram/api/k/a/e;->h:Ljava/util/List;
return-object v0
.end method
.method public final synthetic m()Ljava/lang/Object;
.registers 2
invoke-direct {p0}, Lcom/instagram/api/k/a/e;->b()Lcom/instagram/api/k/a/e;
move-result-object v0
return-object v0
.end method